$(document).ready(function() {
  const apiKey = '9b4b044a77aa3182fadf50c2f4619388';
  let isCelsius = true;
  let currentTempC = null;
  setInterval(() => { $('#dateTime').text(new Date().toLocaleString()); }, 1000);
  $('#getWeatherBtn').click(() => { const city = $('#cityInput').val().trim(); if(city) getWeatherByCity(city); });
  $('#geoBtn').click(() => { if (navigator.geolocation) { navigator.geolocation.getCurrentPosition(pos => { getWeatherByCoords(pos.coords.latitude, pos.coords.longitude); }); } else { $('#message').html('<p class="text-danger">Geolocation not supported!</p>'); } });
  $('#toggleUnitBtn').click(() => { if (currentTempC !== null) { isCelsius = !isCelsius; updateTemperature(); } });
  $('#darkModeBtn').click(() => { $('body').toggleClass('dark-mode'); });
  $('#saveCityBtn').click(() => { const city = $('#cityInput').val().trim(); if(city) { let favs = JSON.parse(localStorage.getItem('favorites')) || []; if (!favs.includes(city)) { favs.push(city); localStorage.setItem('favorites', JSON.stringify(favs)); displayFavorites(); } } });
  displayFavorites();
  $('#cityInput').keypress(e => { if(e.which == 13) $('#getWeatherBtn').click(); });
  $(document).on('click', '.fav-btn', function() { getWeatherByCity($(this).text()); });
  function getWeatherByCity(city) { $('#message').html('<p>Loading...</p>'); $('#weatherCard').addClass('d-none'); $.getJSON(`https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apiKey}&units=metric`).done(data => { displayWeather(data); getForecast(data.coord.lat, data.coord.lon); getAQI(data.coord.lat, data.coord.lon); }).fail(() => $('#message').html('<p class="text-danger">City not found!</p>')); }
  function getWeatherByCoords(lat, lon) { $('#message').html('<p>Loading...</p>'); $('#weatherCard').addClass('d-none'); $.getJSON(`https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=${apiKey}&units=metric`).done(data => { displayWeather(data); getForecast(lat, lon); getAQI(lat, lon); }).fail(() => $('#message').html('<p class="text-danger">Could not fetch weather!</p>')); }
  function displayWeather(data) { $('#cityName').text(`${data.name}, ${data.sys.country}`); currentTempC = data.main.temp; updateTemperature(); $('#humidity').html(`<strong>Humidity:</strong> ${data.main.humidity}%`); $('#wind').html(`<strong>Wind Speed:</strong> ${data.wind.speed} m/s`); $('#description').html(`<strong>Condition:</strong> ${data.weather[0].description}`); $('#weatherIcon').attr('src', `https://openweathermap.org/img/wn/${data.weather[0].icon}@2x.png`); $('#sunrise').html(`<strong>Sunrise:</strong> ${new Date(data.sys.sunrise * 1000).toLocaleTimeString()}`); $('#sunset').html(`<strong>Sunset:</strong> ${new Date(data.sys.sunset * 1000).toLocaleTimeString()}`); $('#weatherCard').removeClass('d-none'); $('#message').html(''); changeBackground(data.weather[0].main); }
  function updateTemperature() { if(isCelsius) { $('#temperature').html(`<strong>Temperature:</strong> ${currentTempC} °C`); $('#toggleUnitBtn').text('Switch to °F'); } else { const tempF = (currentTempC * 9/5 + 32).toFixed(1); $('#temperature').html(`<strong>Temperature:</strong> ${tempF} °F`); $('#toggleUnitBtn').text('Switch to °C'); } }
  function getForecast(lat, lon) { $('#forecast').html(''); $.getJSON(`https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&appid=${apiKey}&units=metric`).done(data => { const daily = {}; data.list.forEach(item => { const date = item.dt_txt.split(' ')[0]; if (!daily[date]) daily[date] = item; }); Object.values(daily).slice(0, 5).forEach(day => { $('#forecast').append(`<div class="col forecast-card"><p>${new Date(day.dt_txt).toLocaleDateString('en-US', { weekday: 'short' })}</p><img src="https://openweathermap.org/img/wn/${day.weather[0].icon}.png" width="50"><p>${day.main.temp.toFixed(0)} °C</p></div>`); }); }); }
  function getAQI(lat, lon) { $.getJSON(`https://api.openweathermap.org/data/2.5/air_pollution?lat=${lat}&lon=${lon}&appid=${apiKey}`).done(data => { const aqiValue = data.list[0].main.aqi; const levels = ["Good 😃", "Fair 🙂", "Moderate 😐", "Poor 😷", "Very Poor 🤢"]; $('#aqi').html(`<strong>Air Quality:</strong> ${levels[aqiValue - 1]}`); }); }
  function changeBackground(condition) { let bg; switch(condition.toLowerCase()) { case 'clear': bg = 'linear-gradient(135deg, #f6d365, #fda085)'; break; case 'clouds': bg = 'linear-gradient(135deg, #bdc3c7, #2c3e50)'; break; case 'rain': bg = 'linear-gradient(135deg, #4e54c8, #8f94fb)'; break; case 'snow': bg = 'linear-gradient(135deg, #e6dada, #274046)'; break; default: bg = 'linear-gradient(135deg, #00c6ff, #0072ff)'; } $('body').css('background', bg); }
  function displayFavorites() { let favs = JSON.parse(localStorage.getItem('favorites')) || []; $('#favorites').html(favs.map(city => `<button class="btn btn-outline-light btn-sm me-1 mb-1 fav-btn">${city}</button>`).join('')); }
});
